name: "Pull Translations"
description: "Pull translations from Transifex for a project and resource"
author: "Lightspeed HQ"
runs:
  using: "node12"
  main: "dist/entrypoint.js"
inputs:
  project:
    description: "Project"
    required: true
  resource:
    description: "Resource"
    required: true
  languages:
    description: "Languages"
    default: "fr,de,nl,es"
    required: true
  mode:
    description: "Mode to pull translations ('default', 'reviewed', 'proofread', 'translator', 'untranslated', 'onlytranslated', 'onlyreviewed', 'onlyproofread', 'sourceastranslation'"
    default: "reviewed"
    required: true
  branch:
    description: "Branch name"
    default: "master"
    required: true
  addPullerAsAssignee:
    description: "Add workflow actor for the pull action as assignee"
    required: false
  addPullerAsReviewer:
    description: "Add workflow actor for the pull action as reviewer"
    required: false